
font.normal={family="FiraCodeNerdFont", style="Regular"}
font.size=14
keyboard.bindings = [
  {key = "Space", mods="Control", chars = "\u0000"},
  {key = "Tab", mods = "Control", chars = "\u001b[27;5;9~"},
  {key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~"},
  {key = "1", mods = "Control", chars = "\u001b[27;5;49~"},
  {key = "2", mods = "Control", chars = "\u001b[27;5;50~"},
  {key = "3", mods = "Control", chars = "\u001b[27;5;51~"},
  {key = "4", mods = "Control", chars = "\u001b[27;5;52~"},
  {key = "5", mods = "Control", chars = "\u001b[27;5;53~"},
  {key = "6", mods = "Control", chars = "\u001b[27;5;54~"},
  {key = "7", mods = "Control", chars = "\u001b[27;5;55~"},
  {key = "8", mods = "Control", chars = "\u001b[27;5;56~"},
  {key = "9", mods = "Control", chars = "\u001b[27;5;57~"},
]

[general]
import = ["~/.alacritty_theme.toml"]
