#!/bin/bash

alias svi='sudo vim -c ":cd %:p:h"'
alias vi='vim -c ":cd %:p:h"'
alias vime='vim -c ":cd %:p:h" -u ~/.vimerc -x'

alias rm='nocorrect rm'
alias mv='nocorrect mv'
alias cp='nocorrect cp'
alias mkdir='nocorrect mkdir'

alias chromium='chromium --enable-plugins --memory-model=low'
alias firefox='firefox 2&> /dev/null &'

alias g='git'
alias gp='git remote | xargs -L 1 git push'

alias spac='sudo pacman-color'
alias pac='pacman-color'
alias cower='cower --color="auto"'
alias y='yaourt'

alias mpc='ncmpc -c -m -S'
alias weechat='weechat-curses'

alias pianobar='/home/tj/system/pianobar'
alias ls='/usr/bin/vendor_perl/ls++'
alias record='ffmpeg -ar 44100 -ac 1 -f alsa -i pulse -f s161e -f x11grab -r 30 -s 1280x720 -i :0+158,93 -vcodec flashsv screengrab.flv'

alias msfconsole='/opt/metasploit/msfconsole'
alias msfpayload='/opt/metasploit/msfpayload'
alias msfencode='/opt/metasploit/msfencode'
alias msfvenom='/opt/metasploit/msfvenom'

alias jelly='/home/tj/workspace/jelly/bin/jelly'

alias rtorrent='tmux attach-session -t rtorrent || tmux new-session -s rtorrent'

function tail_apache() {
    last_file=`\ls -t /var/log/apache2/$1.* | head -1`
    tail $last_file $2
}
alias taa='tail_apache access'
alias tae='tail_apache error'
